// VILLAE ROMANAE — PONTUS site photos. Freely-licensed images from Wikimedia Commons,
// keyed by site id. URL is built at render time via Special:FilePath (see pontus.js).
// Each entry: { file, credit, license, page, caption:{ru,en} }.
// 28 of 34 sites have a free image; the 6 obscure sites (kepoi, patraeus, tyramba,
// apatouron, mamay-kale, raevskoe) have no suitable free photo on Commons yet.
"use strict";

const PONTUS_IMAGES = {
  pantikapaion: { file: "Panticapaeum in Kerch, Ukraine.jpg", credit: "Sergey Ashmarin", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Panticapaeum_in_Kerch,_Ukraine.jpg", caption: { ru: "Руины Пантикапея на горе Митридат, Керчь", en: "Ruins of Panticapaeum on Mount Mithridat, Kerch" } },
  nymphaion: { file: "Nymphaion.Crimea.Excavations.jpg", credit: "Kurgus", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Nymphaion.Crimea.Excavations.jpg", caption: { ru: "Раскопки Нимфея, Крым", en: "Excavations at Nymphaion, Crimea" } },
  theodosia: { file: "Theodosia castle.JPG", credit: "Janmad", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Theodosia_castle.JPG", caption: { ru: "Генуэзская крепость на месте античной Феодосии", en: "Genoese castle on the site of ancient Theodosia" } },
  myrmekion: { file: "Мірмекій.Керч.jpg", credit: "Denis Vitchenko", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Мірмекій.Керч.jpg", caption: { ru: "Археологический комплекс «Мирмекий», Керчь", en: "Archaeological complex of Myrmekion, Kerch" } },
  tyritake: { file: "Рыбозасолочные ванны на Тиритаке.jpg", credit: "Kbda3200", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Рыбозасолочные_ванны_на_Тиритаке.jpg", caption: { ru: "Рыбозасолочные ванны городища Тиритака", en: "Fish-salting vats at the Tyritake site" } },
  iluraton: { file: "Illurat-fortress 1.jpg", credit: "Martin Kisly", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Illurat-fortress_1.jpg", caption: { ru: "Крепость Илурат — вид на долину", en: "Iluraton fortress, view over the valley" } },
  kytaion: { file: "Kitei archeology site.JPG", credit: "Brunei", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Kitei_archeology_site.JPG", caption: { ru: "Раскопки городища Китей", en: "Excavations at the Kytaion site" } },
  porphmion: { file: "Порфмій (3).jpg", credit: "Ewsukow", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Порфмій_(3).jpg", caption: { ru: "Руины городища Порфмий, Керчь", en: "Ruins of the Porthmion site, Kerch" } },
  akra: { file: "Мис Такіль.Фото.jpg", credit: "Neovitaha777", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Мис_Такіль.Фото.jpg", caption: { ru: "Мыс Такиль — у его основания затопленная Акра", en: "Cape Takil — submerged Akra lies at its base" } },
  "kul-oba": { file: "Vas d'or amb representació d'escites, kurgan de Kul-Oba, segona meitat del segle IV aC.JPG", credit: "Joanbanjo", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Vas_d'or_amb_representació_d'escites,_kurgan_de_Kul-Oba,_segona_meitat_del_segle_IV_aC.JPG", caption: { ru: "Золотой сосуд из кургана Куль-Оба, IV в. до н.э.", en: "Gold vessel from the Kul-Oba kurgan, 4th c. BC" } },
  "tsarsky-kurgan": { file: "Royal Kurgan (Kerch).jpg", credit: "Klaus-Norbert", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Royal_Kurgan_(Kerch).jpg", caption: { ru: "Царский курган — монументальная гробница IV в. до н.э.", en: "The Royal Kurgan — monumental 4th-c. BC tomb" } },
  kimmerikon: { file: "Opuk.jpg", credit: "Robert Niedźwiedzki", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Opuk.jpg", caption: { ru: "Гора Опук — место античного Киммерика", en: "Mount Opuk — site of ancient Cimmericum" } },
  "zenon-chersonesos": { file: "Cape.Zyuk-2.jpg", credit: "Kurgus", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Cape.Zyuk-2.jpg", caption: { ru: "Мыс Зюк — место Зенонова Херсонеса", en: "Cape Zyuk — site of Zenonos Chersonesos" } },
  phanagoria: { file: "Раскопки в Фанагории.jpg", credit: "Maria Plotnikova", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Раскопки_в_Фанагории.jpg", caption: { ru: "Раскопки Фанагории — крупнейшего античного городища России", en: "Excavations at Phanagoria, Russia's largest ancient site" } },
  hermonassa: { file: "Hermonassa 5.jpg", credit: "Kmorozov", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Hermonassa_5.jpg", caption: { ru: "Раскопки Гермонассы-Тмутаракани, ст. Тамань", en: "Excavations at Hermonassa-Tmutarakan, Taman" } },
  korokondame: { file: "Tuzla, Kerch Strait, near natural colors satellite image, LandSat-5, 2011-08-30.jpg", credit: "NASA / USGS", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Tuzla,_Kerch_Strait,_near_natural_colors_satellite_image,_LandSat-5,_2011-08-30.jpg", caption: { ru: "Коса Тузла — район Корокондамы (снимок Landsat)", en: "Tuzla Spit — area of Corocondame (Landsat)" } },
  gorgippia: { file: "Anapa. The ancient city of Gorgippia (archaeological site).jpg", credit: "Александр Байдуков", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Anapa._The_ancient_city_of_Gorgippia_(archaeological_site).jpg", caption: { ru: "Раскопки Горгиппии, Анапа", en: "Excavations of Gorgippia, Anapa" } },
  "bata-myskhako": { file: "Мысхако 2023, 01.jpg", credit: "Yuriy75", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Мысхако_2023,_01.jpg", caption: { ru: "Мыс Мысхако, Цемесская бухта — место Баты", en: "Cape Myskhako, Tsemes Bay — site of Bata" } },
  torikos: { file: "Cape Tolsty in Gelendzhik.jpg", credit: "неизв. автор / unknown", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Cape_Tolsty_in_Gelendzhik.jpg", caption: { ru: "Толстый мыс, Геленджик — место Торика (старое фото)", en: "Cape Tolsty, Gelendzhik — site of Torikos (old photo)" } },
  nikopsis: { file: "Остатки крепостного вала крепости Никопсия (Дузу Кале), V-VII вв. н.э..JPG", credit: "Вильма", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Остатки_крепостного_вала_крепости_Никопсия_(Дузу_Кале),_V-VII_вв._н.э..JPG", caption: { ru: "Остатки вала крепости Никопсия (Дузу-Кале), V–VII вв.", en: "Rampart remains of Nikopsia fortress, 5th–7th c." } },
  godlik: { file: "Godlik.JPG", credit: "Ivengo(RUS)", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Godlik.JPG", caption: { ru: "Стена крепости Годлик, Лазаревский район, Сочи", en: "Wall of Godlik fortress, Sochi" } },
  achipse: { file: "Achipse.JPG", credit: "Dmitry Grishin", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Achipse.JPG", caption: { ru: "Крепость Ачипсе, Красная Поляна, Сочи", en: "Achipse fortress, Krasnaya Polyana, Sochi" } },
  tanais: { file: "Танаис, археологический музей-заповедник-7.jpg", credit: "JukoFF", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Танаис,_археологический_музей-заповедник-7.jpg", caption: { ru: "Раскопки Танаиса, музей-заповедник, устье Дона", en: "Excavations at Tanais, Don delta" } },
  chersonesos: { file: "Sebastopol bazilika v bazilike 01.jpg", credit: "Andrew Butko", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Sebastopol_bazilika_v_bazilike_01.jpg", caption: { ru: "«Базилика в базилике» — Херсонес Таврический, Севастополь", en: "Basilica-in-basilica, Chersonesus Taurica, Sevastopol" } },
  kerkinitis: { file: "Городище Керкінітіда. Євпаторія.jpg", credit: "Мандрівниця", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Городище_Керкінітіда._Євпаторія.jpg", caption: { ru: "Городище Керкинитида, Евпатория", en: "Kerkinitis settlement, Yevpatoria" } },
  "kalos-limen": { file: "Калос Лимен - внутри крепости.jpg", credit: "Wikimedia Commons", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Калос_Лимен_-_внутри_крепости.jpg", caption: { ru: "Внутри крепости Калос-Лимен, Черноморское", en: "Inside the Kalos Limen fortress" } },
  "neapolis-scythica": { file: "Simferopol, Scythian Neapolis, 2016.06.17 (05) (29689226505).jpg", credit: "Vahe Martirosyan", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Simferopol,_Scythian_Neapolis,_2016.06.17_(05)_(29689226505).jpg", caption: { ru: "Неаполь Скифский с высоты, Симферополь", en: "Scythian Neapolis from above, Simferopol" } },
  charax: { file: "Charax1.JPG", credit: "Cambronn", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Charax1.JPG", caption: { ru: "Остатки римской крепости Харакс, мыс Ай-Тодор", en: "Remains of the Roman fort Charax, Cape Ai-Todor" } }
};

const PONTUS_IMAGE_URL = (file, w) => "https://commons.wikimedia.org/wiki/Special:FilePath/" + encodeURIComponent(file) + "?width=" + (w || 800);
