// VILLAE ROMANAE — PONTUS site photos. Freely-licensed images from Wikimedia Commons,
// keyed by site id. URL is built at render time via Special:FilePath (see pontus.js).
// Each entry: { file, credit, license, page, caption:{ru,en} }.
// All 35 sites now have an image: 28 are direct site photos; 7 obscure sites with no
// direct free photo on Commons (patraeus, kepoi, tyramba, apatouron, mamay-kale,
// raevskoe, beregovoy-4) use a captioned surrogate — the locality, a neighbouring
// excavated site, or a fitting Bosporan museum artifact.
"use strict";

const PONTUS_IMAGES = {
  pantikapaion: { file: "Panticapaeum in Kerch, Ukraine.jpg", credit: "Sergey Ashmarin", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Panticapaeum_in_Kerch,_Ukraine.jpg", caption: { ru: "Руины Пантикапея на горе Митридат, Керчь", en: "Ruins of Panticapaeum on Mount Mithridat, Kerch" } },
  nymphaion: { file: "Nymphaion.Crimea.Excavations.jpg", credit: "Kurgus", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Nymphaion.Crimea.Excavations.jpg", caption: { ru: "Раскопки Нимфея, Крым", en: "Excavations at Nymphaion, Crimea" } },
  theodosia: { file: "Theodosia castle.JPG", credit: "Janmad", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Theodosia_castle.JPG", caption: { ru: "Генуэзская крепость на месте античной Феодосии", en: "Genoese castle on the site of ancient Theodosia" } },
  myrmekion: { file: "Мірмекій.Керч.jpg", credit: "Denis Vitchenko", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Мірмекій.Керч.jpg", caption: { ru: "Археологический комплекс «Мирмекий», Керчь", en: "Archaeological complex of Myrmekion, Kerch" } },
  tyritake: { file: "Рыбозасолочные ванны на Тиритаке.jpg", credit: "Kbda3200", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Рыбозасолочные_ванны_на_Тиритаке.jpg", caption: { ru: "Рыбозасолочные ванны городища Тиритака", en: "Fish-salting vats at the Tyritake site" } },
  iluraton: { file: "Illurat-fortress 1.jpg", credit: "Martin Kisly", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Illurat-fortress_1.jpg", caption: { ru: "Крепость Илурат — вид на долину", en: "Iluraton fortress, view over the valley" } },
  kytaion: { file: "Kitei archeology site.JPG", credit: "Brunei", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Kitei_archeology_site.JPG", caption: { ru: "Раскопки городища Китей", en: "Excavations at the Kytaion site" } },
  porphmion: { file: "Порфмій (3).jpg", credit: "Ewsukow", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Порфмій_(3).jpg", caption: { ru: "Руины городища Порфмий, Керчь", en: "Ruins of the Porthmion site, Kerch" } },
  akra: { file: "Мис Такіль.Фото.jpg", credit: "Neovitaha777", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Мис_Такіль.Фото.jpg", caption: { ru: "Мыс Такиль — у его основания затопленная Акра", en: "Cape Takil — submerged Akra lies at its base" } },
  // ── Scythian kurgans — carousels (view + animal-style finds), Wikimedia Commons ──
  "kul-oba": [
    { file: "Vas d'or amb representació d'escites, kurgan de Kul-Oba, segona meitat del segle IV aC.JPG", credit: "Joanbanjo", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Vas_d'or_amb_representació_d'escites,_kurgan_de_Kul-Oba,_segona_meitat_del_segle_IV_aC.JPG", caption: { ru: "Электровый сосуд из Куль-Обы со сценами из жизни скифов, IV в. до н.э.", en: "The Kul-Oba electrum vessel with scenes of Scythian life, 4th c. BC" } },
    { file: "KulObaTreasure.jpg", credit: "PHGCOM · Cabinet des Médailles, Paris", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:KulObaTreasure.jpg", caption: { ru: "Золотые бляшки и предметы из сокровищ Куль-Обы", en: "Gold plaques and objects from the Kul-Oba treasure" } },
    { file: "Antiquitsdubos00reinuoft 0241.jpg", credit: "S. Reinach, Antiquités du Bosphore Cimmérien (1892)", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Antiquitsdubos00reinuoft_0241.jpg", caption: { ru: "Находки Куль-Обы в атласе Рейнака (1892)", en: "Kul-Oba finds in Reinach's atlas (1892)" } }
  ],
  kostromskaya: [
    { file: "Placa en forma de cérvol tombat, trobada al túmul de Kostromskoy a Kuban, segle VII aC.JPG", credit: "Joanbanjo", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Placa_en_forma_de_c%C3%A9rvol_tombat,_trobada_al_t%C3%BAmul_de_Kostromskoy_a_Kuban,_segle_VII_aC.JPG", caption: { ru: "«Костромской олень» — золотая бляха-навершие гориты, VII в. до н.э.", en: "The Kostromskaya gold stag — gorytos ornament, 7th c. BC" } },
    { file: "Placca cervo, da regione di krasnodar, kostromskaja, oro fuso e cesellato, inizio VI sec ac.jpg", credit: "Sailko · Государственный Эрмитаж", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Placca_cervo,_da_regione_di_krasnodar,_kostromskaja,_oro_fuso_e_cesellato,_inizio_VI_sec_ac.jpg", caption: { ru: "Золотой олень Костромского кургана в экспозиции Эрмитажа", en: "The Kostromskaya gold stag on display at the Hermitage" } },
    { file: "Horse burials and artifacts of Kostromskaya Kurgan.JPG", credit: "Siyajkak", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Horse_burials_and_artifacts_of_Kostromskaya_Kurgan.JPG", caption: { ru: "Схема конских захоронений и находок Костромского кургана", en: "Diagram of horse burials and finds at the Kostromskaya kurgan" } }
  ],
  kelermes: [
    { file: "Placca pantera, da regione di krasnodar, kurgan chertomlyk, oro a sbalzo e cesellato, fine VII sec ac.jpg", credit: "Sailko · Государственный Эрмитаж", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Placca_pantera,_da_regione_di_krasnodar,_kurgan_chertomlyk,_oro_a_sbalzo_e_cesellato,_fine_VII_sec_ac.jpg", caption: { ru: "Золотая пантера из Келермеса, конец VII в. до н.э. (32,6 см), Эрмитаж", en: "The Kelermes gold panther, late 7th c. BC (32.6 cm), Hermitage" } },
    { file: "Kelermesz.jpg", credit: "Bartuszek", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Kelermesz.jpg", caption: { ru: "Золото Келермесского кургана (репродукция)", en: "Gold from the Kelermes kurgan (reproduction)" } }
  ],
  ulsky: { file: "01976 Навершие в виде стилизованной головы птицы., Краснодарский край. Бронза, литьё. Начало V в. до н.э.jpg", credit: "Триста веков искусства (1976) · Эрмитаж", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:01976_%D0%9D%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%B5_%D0%B2_%D0%B2%D0%B8%D0%B4%D0%B5_%D1%81%D1%82%D0%B8%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D1%8B_%D0%BF%D1%82%D0%B8%D1%86%D1%8B.,_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D0%B4%D0%B0%D1%80%D1%81%D0%BA%D0%B8%D0%B9_%D0%BA%D1%80%D0%B0%D0%B9._%D0%91%D1%80%D0%BE%D0%BD%D0%B7%D0%B0,_%D0%BB%D0%B8%D1%82%D1%8C%D1%91._%D0%9D%D0%B0%D1%87%D0%B0%D0%BB%D0%BE_V_%D0%B2._%D0%B4%D0%BE_%D0%BD.%D1%8D.jpg", caption: { ru: "Бронзовое навершие в виде головы птицы, Ульский курган №2, нач. V в. до н.э.", en: "Bronze bird-head finial, Ulsky kurgan No. 2, early 5th c. BC" } },
  "seven-brothers": [
    { file: "01976 Ажурная пластина в виде профильной птицы, низовье р. Кубани. Бронза, литьё. IV в. до н.э.jpg", credit: "Триста веков искусства (1976) · Эрмитаж", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:01976_%D0%90%D0%B6%D1%83%D1%80%D0%BD%D0%B0%D1%8F_%D0%BF%D0%BB%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0_%D0%B2_%D0%B2%D0%B8%D0%B4%D0%B5_%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9_%D0%BF%D1%82%D0%B8%D1%86%D1%8B,_%D0%BD%D0%B8%D0%B7%D0%BE%D0%B2%D1%8C%D0%B5_%D1%80._%D0%9A%D1%83%D0%B1%D0%B0%D0%BD%D0%B8._%D0%91%D1%80%D0%BE%D0%BD%D0%B7%D0%B0,_%D0%BB%D0%B8%D1%82%D1%8C%D1%91._IV_%D0%B2._%D0%B4%D0%BE_%D0%BD.%D1%8D.jpg", caption: { ru: "Ажурная бронзовая пластина-птица, Семибратний курган №3, IV в. до н.э.", en: "Openwork bronze bird plaque, Seven Brothers kurgan No. 3, 4th c. BC" } },
    { file: "01976 Бляшка в виде головы птицы. Курганмь, низовье р. Кубани. Бронза, литьё. Третья четверть V в. до н.э.jpg", credit: "Триста веков искусства (1976) · Эрмитаж", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:01976_%D0%91%D0%BB%D1%8F%D1%88%D0%BA%D0%B0_%D0%B2_%D0%B2%D0%B8%D0%B4%D0%B5_%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D1%8B_%D0%BF%D1%82%D0%B8%D1%86%D1%8B._%D0%9A%D1%83%D1%80%D0%B3%D0%B0%D0%BD%D0%BC%D1%8C,_%D0%BD%D0%B8%D0%B7%D0%BE%D0%B2%D1%8C%D0%B5_%D1%80._%D0%9A%D1%83%D0%B1%D0%B0%D0%BD%D0%B8._%D0%91%D1%80%D0%BE%D0%BD%D0%B7%D0%B0,_%D0%BB%D0%B8%D1%82%D1%8C%D1%91._%D0%A2%D1%80%D0%B5%D1%82%D1%8C%D1%8F_%D1%87%D0%B5%D1%82%D0%B2%D0%B5%D1%80%D1%82%D1%8C_V_%D0%B2._%D0%B4%D0%BE_%D0%BD.%D1%8D.jpg", caption: { ru: "Бронзовая бляшка-голова птицы, Семибратний курган №2, 3-я четв. V в. до н.э.", en: "Bronze bird-head plaque, Seven Brothers kurgan No. 2, mid-5th c. BC" } }
  ],
  "tsarsky-kurgan": { file: "Royal Kurgan (Kerch).jpg", credit: "Klaus-Norbert", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Royal_Kurgan_(Kerch).jpg", caption: { ru: "Царский курган — монументальная гробница IV в. до н.э.", en: "The Royal Kurgan — monumental 4th-c. BC tomb" } },
  kimmerikon: { file: "Opuk.jpg", credit: "Robert Niedźwiedzki", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Opuk.jpg", caption: { ru: "Гора Опук — место античного Киммерика", en: "Mount Opuk — site of ancient Cimmericum" } },
  "zenon-chersonesos": { file: "Cape.Zyuk-2.jpg", credit: "Kurgus", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Cape.Zyuk-2.jpg", caption: { ru: "Мыс Зюк — место Зенонова Херсонеса", en: "Cape Zyuk — site of Zenonos Chersonesos" } },
  phanagoria: { file: "Раскопки в Фанагории.jpg", credit: "Maria Plotnikova", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Раскопки_в_Фанагории.jpg", caption: { ru: "Раскопки Фанагории — крупнейшего античного городища России", en: "Excavations at Phanagoria, Russia's largest ancient site" } },
  hermonassa: { file: "Hermonassa 5.jpg", credit: "Kmorozov", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Hermonassa_5.jpg", caption: { ru: "Раскопки Гермонассы-Тмутаракани, ст. Тамань", en: "Excavations at Hermonassa-Tmutarakan, Taman" } },
  korokondame: { file: "Tuzla, Kerch Strait, near natural colors satellite image, LandSat-5, 2011-08-30.jpg", credit: "NASA / USGS", license: "Public domain", page: "https://commons.wikimedia.org/wiki/File:Tuzla,_Kerch_Strait,_near_natural_colors_satellite_image,_LandSat-5,_2011-08-30.jpg", caption: { ru: "Коса Тузла — район Корокондамы (снимок Landsat)", en: "Tuzla Spit — area of Corocondame (Landsat)" } },
  gorgippia: { file: "Anapa. The ancient city of Gorgippia (archaeological site).jpg", credit: "Александр Байдуков", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Anapa._The_ancient_city_of_Gorgippia_(archaeological_site).jpg", caption: { ru: "Раскопки Горгиппии, Анапа", en: "Excavations of Gorgippia, Anapa" } },
  "bata-myskhako": { file: "Мысхако 2023, 01.jpg", credit: "Yuriy75", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Мысхако_2023,_01.jpg", caption: { ru: "Мыс Мысхако, Цемесская бухта — место Баты", en: "Cape Myskhako, Tsemes Bay — site of Bata" } },
  torikos: { file: "Cape Tolsty in Gelendzhik.jpg", credit: "неизв. автор / unknown", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Cape_Tolsty_in_Gelendzhik.jpg", caption: { ru: "Толстый мыс, Геленджик — место Торика (старое фото)", en: "Cape Tolsty, Gelendzhik — site of Torikos (old photo)" } },
  nikopsis: { file: "Остатки крепостного вала крепости Никопсия (Дузу Кале), V-VII вв. н.э..JPG", credit: "Вильма", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Остатки_крепостного_вала_крепости_Никопсия_(Дузу_Кале),_V-VII_вв._н.э..JPG", caption: { ru: "Остатки вала крепости Никопсия (Дузу-Кале), V–VII вв.", en: "Rampart remains of Nikopsia fortress, 5th–7th c." } },
  godlik: { file: "Godlik.JPG", credit: "Ivengo(RUS)", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Godlik.JPG", caption: { ru: "Стена крепости Годлик, Лазаревский район, Сочи", en: "Wall of Godlik fortress, Sochi" } },
  achipse: { file: "Achipse.JPG", credit: "Dmitry Grishin", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Achipse.JPG", caption: { ru: "Крепость Ачипсе, Красная Поляна, Сочи", en: "Achipse fortress, Krasnaya Polyana, Sochi" } },
  tanais: { file: "Танаис, археологический музей-заповедник-7.jpg", credit: "JukoFF", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Танаис,_археологический_музей-заповедник-7.jpg", caption: { ru: "Раскопки Танаиса, музей-заповедник, устье Дона", en: "Excavations at Tanais, Don delta" } },
  chersonesos: { file: "Sebastopol bazilika v bazilike 01.jpg", credit: "Andrew Butko", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Sebastopol_bazilika_v_bazilike_01.jpg", caption: { ru: "«Базилика в базилике» — Херсонес Таврический, Севастополь", en: "Basilica-in-basilica, Chersonesus Taurica, Sevastopol" } },
  kerkinitis: { file: "Городище Керкінітіда. Євпаторія.jpg", credit: "Мандрівниця", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:Городище_Керкінітіда._Євпаторія.jpg", caption: { ru: "Городище Керкинитида, Евпатория", en: "Kerkinitis settlement, Yevpatoria" } },
  "kalos-limen": { file: "Калос Лимен - внутри крепости.jpg", credit: "Wikimedia Commons", license: "CC0", page: "https://commons.wikimedia.org/wiki/File:Калос_Лимен_-_внутри_крепости.jpg", caption: { ru: "Внутри крепости Калос-Лимен, Черноморское", en: "Inside the Kalos Limen fortress" } },
  "neapolis-scythica": { file: "Simferopol, Scythian Neapolis, 2016.06.17 (05) (29689226505).jpg", credit: "Vahe Martirosyan", license: "CC BY-SA 2.0", page: "https://commons.wikimedia.org/wiki/File:Simferopol,_Scythian_Neapolis,_2016.06.17_(05)_(29689226505).jpg", caption: { ru: "Неаполь Скифский с высоты, Симферополь", en: "Scythian Neapolis from above, Simferopol" } },
  charax: { file: "Charax1.JPG", credit: "Cambronn", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Charax1.JPG", caption: { ru: "Остатки римской крепости Харакс, мыс Ай-Тодор", en: "Remains of the Roman fort Charax, Cape Ai-Todor" } },
  // — surrogate images: these obscure sites have no direct free photo on Commons; using a locality, neighbouring site, or a fitting Bosporan museum artifact (captioned honestly)
  patraeus: { file: "Музей Горгиппия. Экспонат. (47).jpg", credit: "MikSed", license: "CC BY 4.0", page: "https://commons.wikimedia.org/wiki/File:Музей_Горгиппия._Экспонат._(47).jpg", caption: { ru: "Экспозиция о городах Азиатского Боспора (включая Патрей), Анапский музей «Горгиппия» — фото самих раскопок Патрея в свободном доступе нет.", en: "Exhibit on the towns of the Asian Bosporus (incl. Patraeus), Gorgippia Museum, Anapa — no free photo of the Patraeus dig itself." } },
  kepoi: { file: "Phanagoria excavations (2008).JPG", credit: "kmorozov", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Phanagoria_excavations_(2008).JPG", caption: { ru: "Раскопки Фанагории (≈3 км от Кеп) — ближайший исследованный город на том же берегу Таманского залива.", en: "Excavations at Phanagoria (~3 km from Kepoi) — the nearest excavated city on the same Taman Bay shore." } },
  tyramba: { file: "Вид на пляж за ст. Голубицкая Азовское море - panoramio.jpg", credit: "Nikolay Sizonenko", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Вид_на_пляж_за_ст._Голубицкая_Азовское_море_-_panoramio.jpg", caption: { ru: "Азовский берег Тамани у ст. Голубицкая — та же приморская полоса, где стояла Тирамба (близ ст. Пересыпь).", en: "Azov shore of Taman near Golubitskaya — the same coastal strip where Tyramba stood (near Peresyp)." } },
  apatouron: { file: "2023-08-18. Горгиппия DSC 4679.jpg", credit: "Andrey Butko", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:2023-08-18._Горгиппия_DSC_4679.jpg", caption: { ru: "Терракота сидящей богини (тип Афродиты Урании), Боспор, музей «Горгиппия» — место святилища Апатур пока не найдено.", en: "Terracotta of a seated goddess (Aphrodite Ourania type), Bosporus, Gorgippia Museum — the Apaturon sanctuary is still unlocated." } },
  "mamay-kale": { file: "Mamai1010086.JPG", credit: "Hardsign", license: "CC BY-SA 3.0", page: "https://commons.wikimedia.org/wiki/File:Mamai1010086.JPG", caption: { ru: "Река Мамайка, Сочи — в её устье и стоит городище Мамай-Кале (Мохора).", en: "The Mamayka river, Sochi — the Mamay-Kale (Mokhora) site sits at its mouth." } },
  raevskoe: { file: "Gorgippia.JPG", credit: "Artem Topchiy (Art-top)", license: "CC BY 3.0", page: "https://commons.wikimedia.org/wiki/File:Gorgippia.JPG", caption: { ru: "Раскопки Горгиппии (Анапа) — ближайший задокументированный боспорский памятник к Раевскому городищу (Ногай-Кале).", en: "Excavations at Gorgippia (Anapa) — the nearest documented Bosporan site to the Raevskoe fort (Nogai-Kale)." } },
  "beregovoy-4": { file: "2023-08-18. Горгиппия DSC 4920.jpg", credit: "Andrey Butko", license: "CC BY-SA 4.0", page: "https://commons.wikimedia.org/wiki/File:2023-08-18._Горгиппия_DSC_4920.jpg", caption: { ru: "Терракота Персефоны (Коры), Боспор, музей «Горгиппия» — вотивы такого типа приносили в святилища Деметры и Коры, как «Береговой-4».", en: "Terracotta of Persephone (Kore), Bosporus, Gorgippia Museum — the votive type offered at Demeter & Kore sanctuaries like Beregovoy-4." } }
};

const PONTUS_IMAGE_URL = (file, w) => "https://commons.wikimedia.org/wiki/Special:FilePath/" + encodeURIComponent(file) + "?width=" + (w || 800);
